import Link from "next/link";
import example from "@/public/examples/reviewed-import/walkthrough.json";
import "@/components/monthly/workspace.css";

export const metadata = {
  title: "Reviewed import walkthrough · InfFyn",
  robots: { index: false, follow: false },
};

export default function ReviewedImportExample() {
  return (
    <main className="import-example">
      <nav aria-label="Example navigation">
        <Link href="/demo/monthly">← Company demonstration</Link>
        <Link href="/methodology">Methodology</Link>
      </nav>
      <span className="import-eyebrow">
        SYNTHETIC WALKTHROUGH · GENERATED BY THE ECONOMICS ENGINE
      </span>
      <h1>A cheaper AI bill can still mean more expensive work.</h1>
      <p className="import-example-lead">
        A research firm reduces inference spending, but human review rises and
        fewer deliveries meet acceptance criteria. Reviewed company evidence
        makes that change visible.
      </p>
      <section className="monthly-panel">
        <h2>The monthly result</h2>
        <div
          className="import-table"
          tabIndex={0}
          aria-label="Two-month synthetic economics"
        >
          <table>
            <thead>
              <tr>
                <th>Measure</th>
                <th>July</th>
                <th>August</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th>Inference cost</th>
                {example.months.map((m) => (
                  <td key={m.month}>
                    ${Number(m.inference).toLocaleString("en-US")}
                  </td>
                ))}
              </tr>
              <tr>
                <th>Human review</th>
                {example.months.map((m) => (
                  <td key={m.month}>
                    ${Number(m.human_review).toLocaleString("en-US")}
                  </td>
                ))}
              </tr>
              <tr>
                <th>Total included spend</th>
                {example.months.map((m) => (
                  <td key={m.month}>
                    ${Number(m.spend).toLocaleString("en-US")}
                  </td>
                ))}
              </tr>
              <tr>
                <th>Accepted deliveries</th>
                {example.months.map((m) => (
                  <td key={m.month}>
                    {m.accepted} of {m.reviewed_runs}
                  </td>
                ))}
              </tr>
              <tr>
                <th>Cost per accepted delivery</th>
                {example.months.map((m) => (
                  <td key={m.month}>
                    $
                    {Number(m.cost_per_accepted_outcome).toLocaleString(
                      "en-US",
                      { maximumFractionDigits: 2, minimumFractionDigits: 2 },
                    )}
                  </td>
                ))}
              </tr>
            </tbody>
          </table>
        </div>
        <p>
          <strong>Investigation:</strong> review the extra human work and
          rejected deliveries before treating the lower inference bill as an
          improvement. These observations do not establish what caused the
          change.
        </p>
      </section>
      <section className="monthly-panel">
        <h2>How the evidence reaches the calculation</h2>
        <ol className="import-example-steps">
          <li>
            <strong>Upload the original.</strong> A semicolon-delimited ledger
            has “Cost ID,” “Day” and “Amount” columns. Original bytes stay
            separate from corrections.
          </li>
          <li>
            <strong>Review the mapping.</strong> Map those columns to cost ID,
            date and amount. Confirm USD and the number format. Business IDs
            come from the file.
          </li>
          <li>
            <strong>Resolve exceptions.</strong> Review bad amounts, duplicated
            IDs, exclusions and missing evidence. Every row gets a disposition.
          </li>
          <li>
            <strong>Confirm the version.</strong> The approved dataset has a
            source fingerprint, interpretation and confirmation. It remains
            customer-supplied evidence.
          </li>
          <li>
            <strong>Calculate and repeat.</strong> Attach the confirmed evidence
            to a workload, review scope and save a report. Reuse the rule set
            next month after checking for changed columns and units.
          </li>
        </ol>
      </section>
      <section className="monthly-panel">
        <h2>Inspect the inputs and engine outputs</h2>
        <p>
          These downloads are fixed synthetic fixtures. The editable, persistent
          workflow requires an authenticated company workspace and its database
          migration.
        </p>
        <div className="import-example-downloads">
          {example.months.map((m) => (
            <div key={m.month}>
              <h3>{m.month}</h3>
              {[
                "messy-costs.csv",
                "canonical-costs.csv",
                "outcomes.csv",
                "revenue.csv",
                "report.json",
              ].map((file) => (
                <a
                  key={file}
                  href={`/examples/reviewed-import/${m.month}-${file}`}
                  download
                >
                  {file.replaceAll("-", " ")}
                </a>
              ))}
            </div>
          ))}
        </div>
        <p>
          The $64,000 revenue figure in each fixture is a synthetic management
          allocation. It does not prove revenue was caused by AI.
        </p>
      </section>
      <footer>
        <Link href="/app/monthly">Open authenticated monthly workspace →</Link>
        <p>
          No customer or provider data appears in this example. Hosted recovery
          and authenticated acceptance are separate release checks.
        </p>
      </footer>
    </main>
  );
}
